config/routes.rb
Rails.application.routes.draw do
  ResqueWeb::Engine.eager_load!
  devise_for :users
  require "resque_web"

  IosAlchemy::Application.routes.draw do
    mount ResqueWeb::Engine => "/resque"
  end

  root 'pages#landing'
  get 'home' => 'uploads#home'
  get 'designs' => 'designs#index'

  resources :uploads do
    collection do
      post :create
    end
  end

  resources :designs do
    collection do
      post :create
      post :export_images
    end
  end

  resources :images do
    collection do
      post :list_design_images
      post :download
    end
  end

  resources :ios_screens do
    collection do
      post :export
      post :download
    end
  end

end

app/models/design.rb
class Design < ActiveRecord::Base
  serialize :meta_data
  belongs_to :upload
  has_many :images, dependent: :destroy
  has_many :ios_screens, dependent: :destroy
  enum status: [:incompleted, :completed]

  def extract
  end

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :design
  
  has_attached_file :onex, 
                  :storage => :s3,
                  :s3_credentials => Proc.new{|a| a.instance.s3_credentials }
  has_attached_file :twox, 
                :storage => :s3,
                :s3_credentials => Proc.new{|a| a.instance.s3_credentials }
  has_attached_file :threex, 
                :storage => :s3,
                :s3_credentials => Proc.new{|a| a.instance.s3_credentials }
                  
  validates_attachment_file_name :onex, :matches => [/png\Z/]
  validates_attachment_file_name :twox, :matches => [/png\Z/]
  validates_attachment_file_name :threex, :matches => [/png\Z/]


def s3_credentials
  { 
    bucket: ENV['S3_BUCKET'], 
    access_key_id: ENV['AWS_ACCESS_KEY'],
    secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  }
end

end

app/models/ios_screen.rb
class IosScreen < ActiveRecord::Base
  serialize :formatted_data
  belongs_to :design
end

app/models/upload.rb
class Upload < ActiveRecord::Base

has_attached_file :psd, 
                  :storage => :s3,
                  :s3_credentials => Proc.new{|a| a.instance.s3_credentials }
has_attached_file :psd_image, 
                  :storage => :s3,
                  :s3_credentials => Proc.new{|a| a.instance.s3_credentials }
                  
validates_attachment_file_name :psd, :matches => [/psd\Z/]
validates_attachment_file_name :psd_image, :matches => [/png\Z/]

enum status: [:incompleted, :completed]

belongs_to :user
has_one :design, dependent: :destroy
def s3_credentials
  { 
    bucket: ENV['S3_BUCKET'], 
    access_key_id: ENV['AWS_ACCESS_KEY'],
    secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  }
end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :uploads, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :layout_by_resource

   protected

  def layout_by_resource
    if devise_controller?
      "device"
    end
  end
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
  end

  def show
    @design = Design.find(params[:id])
  end

  def index
  end

  def export_images
    design = Design.find(params[:id])
    if Resque.enqueue ExtractJob, design.id
         redirect_to uploads_path , notice: 'Design is queued for extraction. You can view all extracted images in the images section in a short while'
    end
  end
end

app/controllers/images_controller.rb
require 'rubygems'
require 'zip'
require "open-uri"


class ImagesController < ApplicationController
  before_action :authenticate_user!

  def index
    # @designs = current_user.designs.completed
    @designs = []
    uploads = current_user.uploads
    uploads.each do |upload|
      @designs << upload.design if upload.design.completed?
    end
    @designs
  end

  def show
    design  = Design.find(params[:design_id])
    @images = design.images
  end

  def download
    design  = Design.find(params[:design_id])
    @images = design.images
    zip_file_name = "tmp/image-export#{Time.now}.zip"
    Zip::File.open(zip_file_name, Zip::File::CREATE) do |zipfile|
      @images.each do |image|
        image.onex.copy_to_local_file(:original, "tmp/#{image.onex_file_name}")
        image.twox.copy_to_local_file(:original, "tmp/#{image.twox_file_name}")
        image.threex.copy_to_local_file(:original, "tmp/#{image.threex_file_name}")
        zipfile.add(image.onex_file_name, "tmp/#{image.onex_file_name}")
        zipfile.add(image.twox_file_name, "tmp/#{image.twox_file_name}")
        zipfile.add(image.threex_file_name, "tmp/#{image.threex_file_name}")
      end
    end

    send_file zip_file_name, :type => 'application/zip',
                                 :disposition => 'attachment',
                                 :filename => "Image_exports.zip"
                                 

  end
end
 
  

app/controllers/ios_screens_controller.rb
require 'rubygems'
require 'zip'
require "open-uri"

class IosScreensController < ApplicationController
  before_action :authenticate_user!

  def index
     @designs = []
     uploads = current_user.uploads
    uploads.each do |upload|
      @designs << upload.design if upload.design.ios_screens.count > 0
    end
    @designs
  end

  def export
    design = Design.find(params[:design_id])
    if Resque.enqueue IosConversionJob, design.id
      redirect_to uploads_path, notice: 'Design is queued for ios conversion. You can view the converted files in the ios section'
    end
  end

  def download
    design  = Design.find(params[:design_id])
    data = design.ios_screens.first.formatted_data
    xib_file_name = "screen-#{Time.now}.xib"
    File.write("tmp/#{xib_file_name}",data)

   send_file "tmp/#{xib_file_name}", 
                                 :disposition => 'attachment',
                                 :filename => "ios_screen.xib"


  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   before_action :authenticate_user!, :except => [:landing]

  def landing
     render(:layout => "layouts/landing")
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :authenticate_user!

  def index
    @uploads = current_user.uploads.completed
  end
  def home
    @uploads= current_user.uploads.completed
  end
  
  def new
    @upload = Upload.new
  end

  def create
    @upload = current_user.uploads.new psd: URI.parse(URI.unescape(params['url']))
    respond_to do |format|
      if @upload.save
        Resque.enqueue PsdJob, @upload.id
        format.html { redirect_to :home, notice: 'PSD was successfully uploaded.' }
        format.json { render :show, status: :created, location: @upload }
      else
        format.html { render :new }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def upload_params
    params.require(:upload).permit(:psd)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/ios_helper.rb
module IosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/designs/_side_bar_tree.html.erb
<ul class="nav nav-sidebar">
  <div id="tree1"></div>
</ul>

<script type ="text/javascript">

$('#tree1').tree({
    data: <%= raw @design.meta_data.to_json %>,
    autoOpen: true,
    dragAndDrop: true
});
</script>

app/views/designs/index.html.erb
<%= render 'side_bar_tree' %>

app/views/designs/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= render 'side_bar_tree' %>
  </div>
  <div class="col-md-8">
  <div class="row">
  <%= button_to "Download all images in this design", {action: "export_images", id: @design.id, method: :post } , class: "btn btn-danger download-button" %>

    <%= button_to "Convert this file to iOS Screen", {controller: "ios_screens", action: "export", design_id: @design.id, method: :post } , class: "btn btn-danger download-button" %>
  </div>
</div>

app/views/images/_image.html.erb
    <div class="row image-view">
      <div class="col-md-3 image-box well">
      <%= image_tag(image.onex, class: "image-thumbnail")%>
        <p><%= image.onex_file_name %></p>

      </div>
      <div class="col-md-3 image-box well">
      <%= image_tag(image.twox, class: "image-thumbnail")%>
        <p><%= image.twox_file_name %></p>

      </div>
      <div class="col-md-3 image-box well">
      <%= image_tag(image.threex, class: "image-thumbnail")%>
        <p><%= image.threex_file_name %></p>

      </div>
      <div class="caption">
      </div>
    </div>

app/views/images/index.html.erb
<% @designs.each do |design| %>
    <%= link_to(controller: "images", action: "list_design_images", design_id: design.id) do %>
    <div class="well col-md-3 col-md-offset-1 caption">
        <h3 class="upload-title"><%= design.upload.psd_file_name %></h3>
    </div>
<% end %>
<% end %>


    

app/views/images/show.html.erb
<%= button_to "Download Images", {action: "download", design_id: @images.first.design_id, method: :post } , class: "btn btn-danger" %>

<div id="uploads">
  <%= render @images %>



</div>

app/views/ios_screens/index.html.erb
<% @designs.each do |design| %>
  <h6 class="upload-title"></h6>
    <div class=" col-md-3 col-md-offset-1 caption">
    <%= button_to "Download screen for #{design.upload.psd_file_name}", {action: "download", design_id: design.id, method: :post } , class: "btn btn-danger" %>
     </div>
<% end %>


    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iOS Alchemy</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
   <!-- Navigation -->
    <nav class="navbar  navbar-default navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a  href="/"><img src="/logo_small.jpg"/></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav pull-right">
                  <% if user_signed_in? %>
                    <li><%= link_to current_user.email, edit_user_registration_path, :class => 'navbar-link' %></li>
                    <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
                  <% else %>
                    <li><%= link_to "Register", new_user_registration_path, :class => 'navbar-link'  %></li>
                    <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
                  <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container view-container">

      <div class="row text-center">
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav nav-sidebar">
                <li><a href="<%= home_path %>">UPLOAD PSD</a></li>
                <li><a href="<%= uploads_path %>">MY UPLOADS</a></li>
                <li><a href="<%= images_path %>">EXPORTED IMAGES</a></li>
                <li><a href="<%= ios_screens_path %>">iOS EXPORTS</a></li>
              </ul>
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
              <div class="row text-center">
                <div class="container-fluid">
                  <% if notice %>
                    <p class="alert alert-success"><%= notice %></p>
                  <% end %>
                  <% if alert %>
                    <p class="alert alert-danger"><%= alert %></p>
                  <% end %>
              </div>
              <div class="main-container row">

                <%= yield %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /.container -->

    <div class="container">
      <hr>
       <!-- Footer -->
      <footer>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/device.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Navigation -->
    <nav class="navbar  navbar-default navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a  href="/"><img src="/logo_small.jpg"/></a>
            </div>
    </nav>
    <div class="container">
  
  <%= yield %>
  </div>
</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'pages', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  
  
  <%= yield %>
</body>
</html>

app/views/pages/landing.html.erb
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
    <img src="logo.jpg"/>
      <div class="row tagline">
        <p class="lead col-md-6 col-md-offset-3">Magical Process of transmuting PSD into iOS screens  </p>
      </div>
      <div class="row ">
         <img class = "cover-pic col-md-10 col-md-offset-1" src="lab.gif"/>
       </div>
          <a href="<%= home_path %>" class="btn btn-lg btn-default upload-button">Let the magic begin - <b>Upload PSD</b></a>
        </p>
    </div>
  </div>
</div>

app/views/uploads/_upload.html.erb
  <a href = "<%= design_path(id: upload.design.id )%>">
  <div class="col-md-3 col-sm-6 upload-box">
    <div class="thumbnail">
      <%= image_tag(upload.psd_image)%>
      <div class="caption">
        <h3 class="upload-title"><%= upload.psd_file_name %></h3>
      </div>
    </div>
  </div>
</a>

app/views/uploads/home.html.erb
<div class ="row">
  <img class="psd-img" src="psd.jpg"/>
</div>
<p class="file-upload-text">Choose and upload PSD</p>
<%= s3_uploader_form callback_url: uploads_url, callback_param: "upload[psd_url]", id: "s3-uploader" do %>
<%= file_field_tag :file, multiple: true%>
<input type='file' id='file' name='file' multiple: "true" />
<a href="#" class = "btn btn-lg btn-danger file-upload-button" id='link-upload'>Upload</a>

<% end %>
<div id="uploads_container"></div>
  <script id="template-upload" type="text/x-tmpl">
  <div id="upload_{%=o.unique_id%}" class="upload">
  <h5>{%=o.name%}</h5>
  <div class="progress progress-striped active"><div class="bar" style="width: 0%"></div></div>
  </div>
  </script>

  <script type="text/javascript">
  $(function(){
    $('#link-upload').click(function(e){
      e.preventDefault();
      $('#file').click();
    });
  });
</script>
</div>

app/views/uploads/index.html.erb
<div id="uploads">
  <%= render @uploads %>
</div>